### PR TITLE
tsave function bug

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### Reference Issues/PRs
#113 
#### What does this implement/fix? Explain your changes.
- `tsave` function bug in Windows fixed

### CODE REVIEW

**Comment by sepandhaghighi** [comment]
@ssheikholeslami @sadrasabouri 

Hi folks ;-)

This PR is for #113 , please check carefully and give me some feedback ;-)
We should run some manually test and complete this table before merging : 

## Windows
1. [ ] Run `tsave` in Windows (ASCII font)
    - [ ] Transfer to Linux 
    - [ ] Transfer to OSX 
2. [ ] Run `tsave` in Windows (Non-ASCII font)
    - [ ] Transfer to Linux 
    - [ ] Transfer to OSX 
## Linux
1. [ ] Run `tsave` in Linux (ASCII font)
    - [ ] Transfer to Windows 
    - [ ] Transfer to OSX 
2. [ ] Run `tsave` in Linux (Non-ASCII font)
    - [ ] Transfer to Windows 
    - [ ] Transfer to OSX 

## OSX
1. [ ] Run `tsave` in OSX (ASCII font)
    - [ ] Transfer to Windows 
    - [ ] Transfer to Linux 
2. [ ] Run `tsave` in OSX (Non-ASCII font)
    - [ ] Transfer to Windows 
    - [ ] Transfer to Linux


**Notice 1** : Do not hurry, we have enough time ;-)
**Notice 2** : Test `tsave-bug` branch
**Notice 3** : This PR has 2 reviewer, so please don't merge this PR to `dev` branch before finishing the discussion

**Comment by sadrasabouri** [comment]
> @ssheikholeslami @sadrasabouri
> 
> Hi folks ;-)
> 
> This PR is for #113 , please check carefully and give me some feedback ;-)
> We should run some manually test and complete this table before merging :
> ## Windows
> 
>     1. [ ]  Run `tsave` in Windows (ASCII font)
>        
>        * [ ]  Transfer to Linux
>        * [ ]  Transfer to OSX
> 
>     2. [ ]  Run `tsave` in Windows (Non-ASCII font)
>        
>        * [ ]  Transfer to Linux
>        * [ ]  Transfer to OSX
> 
> 
> ## Linux
> 
>     1. [x]  Run `tsave` in Linux (ASCII font)
>        
>        * [x]  Transfer to Windows
>        * [x]  Transfer to OSX
> 
>     2. [x]  Run `tsave` in Linux (Non-ASCII font)
>        
>        * [x]  Transfer to Windows
>        * [x]  Transfer to OSX
> 
> 
> ## OSX
> 
>     1. [ ]  Run `tsave` in OSX (ASCII font)
>        
>        * [ ]  Transfer to Windows
>        * [ ]  Transfer to Linux
> 
>     2. [ ]  Run `tsave` in OSX (Non-ASCII font)
>        
>        * [ ]  Transfer to Windows
>        * [ ]  Transfer to Linux
> 
> 
> **Notice 1** : Do not hurry, we have enough time ;-)
> **Notice 2** : Test `tsave-bug` branch
> **Notice 3** : This PR has 2 reviewer, so please don't merge this PR to `dev` branch before finishing the discussion

@sepandhaghighi @ssheikholeslami 
I ran `tsave` in ubuntu-Linux envairement and transferred results (for both ASCII and none-ASCII font using `block_dic` and `fancy11` respectively) to Windows and OSX, they were :ok: .

**Comment by sepandhaghighi** [comment]
> > @ssheikholeslami @sadrasabouri
> > Hi folks ;-)
> > This PR is for #113 , please check carefully and give me some feedback ;-)
> > We should run some manually test and complete this table before merging :
> > ## Windows
> > ```
> > 1. [ ]  Run `tsave` in Windows (ASCII font)
> >    
> >    * [ ]  Transfer to Linux
> >    * [ ]  Transfer to OSX
> > 
> > 2. [ ]  Run `tsave` in Windows (Non-ASCII font)
> >    
> >    * [ ]  Transfer to Linux
> >    * [ ]  Transfer to OSX
> > ```
> > 
> > 
> > ## Linux
> > ```
> > 1. [x]  Run `tsave` in Linux (ASCII font)
> >    
> >    * [x]  Transfer to Windows
> >    * [x]  Transfer to OSX
> > 
> > 2. [x]  Run `tsave` in Linux (Non-ASCII font)
> >    
> >    * [x]  Transfer to Windows
> >    * [x]  Transfer to OSX
> > ```
> > 
> > 
> > ## OSX
> > ```
> > 1. [ ]  Run `tsave` in OSX (ASCII font)
> >    
> >    * [ ]  Transfer to Windows
> >    * [ ]  Transfer to Linux
> > 
> > 2. [ ]  Run `tsave` in OSX (Non-ASCII font)
> >    
> >    * [ ]  Transfer to Windows
> >    * [ ]  Transfer to Linux
> > ```
> > 
> > 
> > **Notice 1** : Do not hurry, we have enough time ;-)
> > **Notice 2** : Test `tsave-bug` branch
> > **Notice 3** : This PR has 2 reviewer, so please don't merge this PR to `dev` branch before finishing the discussion
> 
> @sepandhaghighi @ssheikholeslami
> I ran `tsave` in ubuntu-Linux envairement and transferred results (for both ASCII and none-ASCII font using `block_dic` and `fancy11` respectively) to Windows and OSX, they were 🆗 .

Thanks for your effort 👍

**Comment by sepandhaghighi** [comment]
@sadrasabouri I tested both files in Windows, LGTM ;-)

**Comment by sepandhaghighi** [comment]
@ssheikholeslami Would you please test `tsave` function with some different fonts (ASCII and Non-ASCII) on your system and give me some feedback ?

**Comment by sepandhaghighi** [comment]
@ssheikholeslami 
Just a friendly reminder! ⏲

**Pull request merged**
